//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KkutuMemo.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KkutuMemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   가면라이더뉴제네레이션닥터팩맨대이그제이드앤드고스트위드레전드라이더 만화/애니메이션 어인정
        ///가면라이더뉴제네레이션파이널빌드앤드이그제이드위드레전드라이더 만화/애니메이션 어인정
        ///가면라이더가면라이더고스트앤드드라이브초무비대전제네시스 만화/애니메이션 어인정
        ///가끔씩툭하고러시아어로부끄러워하는옆자리의아랴양 라이트노벨 어인정
        ///가디언즈오브더갤럭시볼륨3가디언즈디스어셈블드 만화/애니메이션 어인정
        ///가챠를돌려동료를늘리고최강의미소녀군단을만들자 라이트노벨 어인정
        ///가브리엘이글레시아스푹신한개그맨의기아체험 넷플릭스 어인정
        ///가디언즈오브더갤럭시볼륨1코스믹어벤저스 만화/애니메이션 어인정
        ///가족을아끼는바다민족의슈퍼아쿠아토네이도 포켓몬스터 어인정
        ///가끔미치도록네가안고싶어질때가있어 한국대중음악 어인정
        ///가로세로세계사4캐나다호주뉴질랜드 만화/애니메이션 어인정
        ///가벼운그녀석과트라우마극복엑스엑스 만화/애니메이션 어인정
        ///가브리엘이글레시아스스타디움플러피 넷플릭스 어인정
        ///가장아름다운괴물이저자신을괴롭힌다 소설/시/희곡 어인정
        ///가장질긴족쇄가장지긋지긋한[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _long {
            get {
                return ResourceManager.GetString("_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ㄱ낫 
        ///ㄱ자촉홈 
        ///ㄱ자턱솔홈 
        ///ㄱ자홈 
        ///가갸 
        ///가끔 
        ///가끔씩 
        ///가격인덱세이션 
        ///가뀌 
        ///가넷 
        ///가는개여뀌 
        ///가늠값 
        ///가늣 
        ///가대기꾼 
        ///가도멸괵 
        ///가돌리늄 
        ///가동댐 
        ///가듁 
        ///가드스웹 어인정
        ///가든골렘 어인정
        ///가이드스틱 어인정
        ///가락지매듭 
        ///가랒 
        ///가래꾼 
        ///가래질꾼 
        ///가래톳 
        ///가렌 어인정
        ///가렛좃 
        ///가로무늬 
        ///가뢰꾼 
        ///가마꾼 
        ///가만사뿐 
        ///가무슥 
        ///가뭄 
        ///가뿍 
        ///가뿍가뿍 
        ///가뿐 
        ///가뿐가뿐 
        ///가살꾼 
        ///가스뷰렛 
        ///가스블랙 
        ///가슴으로외쳐 어인정
        ///가슴팍 
        ///가시덩굴사냥꾼 어인정
        ///가시덤불여뀌 
        ///가시물그릇 
        ///가시스펙트럼 
        ///가시여뀌 
        ///가얌버슷 
        ///가오슝 
        ///가요무늬 
        ///가을에부쳐 어인정
        ///가을이긴한가봐 어인정
        ///가야컨트리클럽 어인정 한방
        ///가평베네스트골프클럽 어인정 한방
        ///가잠나릇 
        ///가재무릇 
        ///가제무릇 
        ///가중값 
        ///가는밸 
        ///가지방석매듭 
        ///가지찜 
        ///가취꿋 
        ///가측값 
        ///가운데톨 
        ///가톨 
        ///가칫 
        ///가칫가칫 
        ///가쾨 
        ///가틱가틱 
        ///가루[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string attack {
            get {
                return ResourceManager.GetString("attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   갇긴 
        ///갇모 
        ///갇힌하늘 어인정
        ///갓김치 
        ///갓버섯 
        ///갓붑 
        ///갓세븐 어인정 한방
        ///갓훠 
        ///값같은선 
        ///값어치 
        ///값없이 
        ///값전자 
        ///값표 
        ///갖갖 
        ///갖은것 
        ///갚음 
        ///갤갤 
        ///갤러핑인플레이션 
        ///갤럭시원격서비스 어인정
        ///갬블마스터 어인정
        ///갯값 
        ///갸름 
        ///갸름갸름 
        ///갸우뚱 
        ///갸우뚱갸우뚱 
        ///갸웃 
        ///갸웃갸웃 
        ///걀쑴걀쑴 한방
        ///걍그영화 
        ///걔네들분명했을걸 어인정
        ///걔말고 어인정
        ///걔세 어인정
        ///것셥 
        ///겉눈썹 
        ///겉잣 
        ///게르마늄 
        ///게르만족 
        ///겟백 어인정
        ///겥붙이 
        ///겪이 
        ///겯거니틀거니 
        ///겻곳비 
        ///겻눈 
        ///겻문 
        ///겻자리 
        ///겻조치 
        ///겻집 
        ///곗날 
        ///곗돈 
        ///곗술 
        ///곗일 
        ///곪기 
        ///곪음 
        ///곬말장그물 
        ///곬섶 
        ///곬수채 
        ///곬온돌 
        ///곶닢 
        ///곽수종의뉴스정면승부 어인정
        ///곽수종의생생경제 어인정
        ///괌섬 
        ///괏쇠 
        ///괘법동 어인정
        ///괘법르네시떼역 어인정
        ///괘종시계 어인정
        ///괵상미 
        ///괸돌 
        ///괸믈 
        ///굄대 
        ///굄돌 
        ///굄목 
        ///굄새 
        ///굄성 
        ///굄질 
        ///굇마리 
        ///굉굉 
        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string defense {
            get {
                return ResourceManager.GetString("defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가녘 한방
        ///가뜩 한방
        ///가뜩가뜩 한방
        ///가린긿 한방
        ///가마후렁 한방
        ///가벼운피읖 한방
        ///가뿟 한방
        ///가뿟가뿟 한방
        ///가읅 한방
        ///가짓부렁 한방
        ///가쯘가쯘 한방
        ///가스포켓 한방
        ///간두렁 한방
        ///갈구렁 한방
        ///갓세븐 한방 어인정
        ///강녘 한방
        ///개그야놀아줘 한방 어인정
        ///개녘 한방
        ///개를돌봐줘 한방 어인정
        ///개리슨 한방
        ///개보다사랑해줘 한방 어인정
        ///개울녘 한방
        ///갤쯤갤쯤 한방
        ///갯불녘 한방
        ///걀쑴걀쑴 한방
        ///걀쯤 한방
        ///걀쯤걀쯤 한방
        ///거기있어줘 한방 어인정
        ///거들렁거들렁 한방
        ///거듧 한방
        ///거렁거렁 한방
        ///거르렁 한방
        ///거르렁거르렁 한방
        ///거먕 한방
        ///거뿟 한방
        ///거뿟거뿟 한방
        ///거욷 한방
        ///거짓부렁 한방
        ///거품안넘치게따라줘 한방 어인정
        ///건드렁 한방
        ///건드렁건드렁 한방
        ///건반위의파쇨 한방 어인정
        ///건앤드헤븐 한방 어인정
        ///걸그렁 한방
        ///걸그렁걸그렁 한방
        ///검투사드레이븐 한방 어인정
        ///게이머즈헤븐 한방 어인정
        ///게이트세븐 한방 어인정
        ///겟이븐 한방 어인정
        ///결련태껸 한방
        ///결혼해줘 한방 어인정
        ///고기시렁[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string hanbang {
            get {
                return ResourceManager.GetString("hanbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] NanumSquareNeo {
            get {
                object obj = ResourceManager.GetObject("NanumSquareNeo", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
